### ISSUE TITLE
Signin sessionが上手くいかない

### ISSUE THREAD

**Issue by DogKingFun** [DogKingFun/sns_template#1]
passportに存在するメソッドのserializeUserとdeserializeUserが動作していない。
serializeUserを動作させようとすれば

server    | TypeError: req.session.regenerate is not a function
server    |     at SessionManager.logIn (/usr/src/server/node_modules/passport/lib/sessionmanager.js:28:15)
server    |     at req.login.req.logIn (/usr/src/server/node_modules/passport/lib/http/request.js:39:26)
server    |     at strategy.success (/usr/src/server/node_modules/passport/lib/middleware/authenticate.js:256:13)
server    |     at verified (/usr/src/server/node_modules/passport-local/lib/strategy.js:83:10)
server    |     at Strategy._verify (/usr/src/server/config/passport.js:48:11)

というエラーが吐かれる。問題解決には海外のディスカッション( https://stackoverflow.com/questions/72375564/typeerror-req-session-regenerate-is-not-a-function-using-passport )からpassportのバージョンを下げることで対応できるのではと考えている。

**Comment by DogKingFun** [comment]
ほんとにマジでpassportのバージョンを下げたら解決したよ畜生
